### ISSUE TITLE
Parser for Injection Info :(

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#106]
# User story
As a user, I want injection information (such as injection volume, etc) parsed from comments in Labtracks.

# Acceptance criteria
- [x] Find regex patterns in comments that can be parsed 
- [x] Write parsing method 

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined
- [x] 2. Team understands acceptance criteria
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria
- [x] 4. Acceptance criteria is verifiable / testable
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
VT is the viral prep lot number, CN is the plasmid construct number, and the number (5.00E+11) is the dose (or genome copy). All of this connects to TARS

**Comment by mekhlakapoor** [comment]
Blocked because of Injection Material 'name' -- need to figure out TARS viral info

**Comment by jtyoung84** [comment]
Closing this as it will be incorporated in TARS ticket
