### ISSUE TITLE
2023 Craniotomy workstation id is being pulled from injection workstation id

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#112]
**Describe the bug**
When a cranitotomy procedure is constructed, the workstation id is being pulled from the injection workstation id instead of the headpost workstation id

**To Reproduce**
1. Go to unit tests and check list_item10 and mapped_list_item10
2. Notice the workstation_id for the craniotomy procedure is null

**Expected behavior**
The workstation id should be pulled from "HpWorkStation" field

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mekhlakapoor** [comment]
On the 2023 endpoint, workstation ID is based on the time of procedure (if it was "Initial Surgery" or "Followup Surgery", so it's not necessarily true that specific workstation id fields correlate with specific procedures.
