### ISSUE TITLE
Some procedure dates missing/incorrect in 2019 sharepoint DB

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#122]
**Describe the bug**
The procedures for subject 652505 have the following issues:
- the second procedure has `null` start+end date (this procedure happened on the same day as the third procedure)
- RobH reports that 2019 DB lists has the 3rd procedure dated at 2022-9-30. Service is reporting 2022-11-18.

**To Reproduce**
1. Go to http://aind-metadata-service/procedures/652505

**Acceptance Criteria**
- second procedure should have the same date as the third procedure
- confirm that both procedures are getting their date from the correct DB field

**Comment by jtyoung84** [comment]
Duplicated
