### ISSUE TITLE
Handle sharepoint 2023 db schema changes

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#123]
From Rob: 

>  For the 2023 database the fields below are now in number format. We ended up breaking out the D/V into 3 fields to account for multiple depths. Finally we now have the option for 6 burr holes so # can be 1-6.
>> Burr # Angle
>> Burr # A/P
>>Inj#volperdepth
>>Burr # M/L
>>Burr # D/V 1
>>Burr # D/V 2
>>Burr # D/V 3
>>Fiber Implant D/V

**Comment by mekhlakapoor** [comment]
- [ ] remove str parsers for number format fields 
- [ ] map burr dv list (from Burr D/V 1-3)
- [ ] map burr holes #5-6
