### ISSUE TITLE
More than one perfusion

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#131]
**Describe the bug**
Subject id 661278 has 2 perfusions from LAS database. This is not possible as a perfusion can only be performed once. This might be a big issue this can be happening for other subjects. Find out how fake perfusions are being tracked in LAS and update procedures mapping in labtracks endpoint. Also look into whether there are other subject ids with multiple perfusions

**To Reproduce**
1. search subject id 661278 with aind-metadata-service
2. See 2 perfusions

**Expected behavior**
Only one perfusion

**Additional context**

**Comment by saskiad** [comment]
from the LAS email it sounds like there is a field in LabTracks for canceled procedures that we need to be looking at
