### ISSUE TITLE
Client for SmartSheet

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#142]
Add a client that can pull perfusion procedure records from this SmartSheet:
https://app.smartsheet.com/sheets/j9VhHXXP6CVG299449gpgwFC37V2X4GVw6VVQFW1?view=grid

**Comment by jtyoung84** [comment]
Notes: It looks like this ticket languished in Sprint Ready for a while. The actual task only took a couple of days. I think upgrading to pydantic v2 took a large chunk of time. There were other unforeseen high priority tasks like updating the CodeOcean API that also took some precedent. Maybe we can add some checks on how long a ticket has been in  particular column.
