### ISSUE TITLE
Missing Cage and Room Ids

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#145]
**Describe the bug**
For subjects that are missing cage and room information, the metadata service is returning -99999999999999 (invalid return value). 

**To Reproduce**
1. Search for subject info for subject_id=632269. 
2. See that cage_id=-99999999999999, room_id=-99999999999999
3. See in the UI that cage number is "Empty"

**Expected behavior**
We expect that if cage or room id is missing, that it returns None. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saskiad** [comment]
it sounds like this is going to be true for any subject that has been euthanized - which makes the housing information useless to us and we should probably remove it from the schema. Let's discuss in a planning meeting.

**Comment by mekhlakapoor** [comment]
Moving this ticket to blocked until we have this discussion.
