### ISSUE TITLE
Fetch instrument.json and rig.json from SLIMS

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#149]
- [x] http://aind-metadata-service/instrument/<instrument_name> exists
- [x] route queries SLIMS for an Instrument by its name
- [x] downloads the most recently attached file
- [x] Makes an Instrument model or Rig model depending on SLIMS Instrument type
- [x] render to a response

**Comment by mekhlakapoor** [comment]
@jtyoung84 @mekhlakapoor Link #175 and #174

**Comment by mekhlakapoor** [comment]
Closed by #177 and #176
