### ISSUE TITLE
Update procedures model

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#153]
# User story
As a user, I want the latest valid procedures model from aind-data-schema (0.9.5?)

# Acceptance criteria
- [ ] Given current version, check validation errors when validated against latest version. 
- [ ] Update pinned version of aind-data-schema.
- [ ] Check any additions from NSB
- [ ] Handle mapping changes

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by jtyoung84** [comment]
@mekhlakapoor Is this finished with the upgrade to v1.0?

**Comment by mekhlakapoor** [comment]
> @mekhlakapoor Is this finished with the upgrade to v1.0?

Yes it's finished. We can go ahead and close this ticket as done.
