### ISSUE TITLE
Fix Merge Responses

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#154]
**Describe the bug**
As a user, I want the client errors to better reflect the issues at hand. The procedures endpoint is currently not combining the 2 different messages from sharepoint and labtracks correctly

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saskiad** [comment]
service returns "valid model" when required fields are missing
eg. http://aind-metadata-service/procedures/653980
This says the model is valid but there is no injection_volume field, which is a required field.

**Comment by mekhlakapoor** [comment]
> service returns "valid model" when required fields are missing eg. http://aind-metadata-service/procedures/653980 This says the model is valid but there is no injection_volume field, which is a required field.

Created a new issue for this #158
