### ISSUE TITLE
Map response from TARS to ModelResponse object

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#165]
# User story
As a user, I want to map the information from TARS into our internal model, so I can integrate this information into a common schema.

# Acceptance criteria
- [x] Given a response is received from TARS, then a function can be called that will map that response to an Optional[InjectionMaterial]
- [x] If there is an error receiving information from TARS, then the beforementioned function will return an InternalServerError response
- [x] Given there is an error with connecting to TARS, an error message will be logged

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined
- [x] 2. Team understands acceptance criteria
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria
- [x] 4. Acceptance criteria is verifiable / testable
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
Notes: This ticket's task only took a couple days (I had some of the work from the previous ticket already done), but the review process took a while -- it was there for 5 days before I messaged a reminder so maybe I'll do that earlier. After review, it was unclear whether to handle the molecular registry check within this PR or separately
