### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#17]
**Describe the bug**
When entered string to create a LabTracksClient has a typo, the error message thrown does not indicate a typo which can be confusing for a user. Throw a clearer error message to indicate the mistake

**To Reproduce**
1. Build a docker image and run python
2. create a labtracks client (ltc) 
3. ltc=LabTracksClient(driver="{FreeTDS}", server="10.128.104.19", port="58350", db="LabTracks_AIBS",user="limstracks", password=“*****”) 
4. create session (session=ltc.create_session())
5. View thrown error

**Expected behavior**
Should throw error that the password was incorrect/had a typo when creating the LabTracks client

**Screenshots**
<img width="562" alt="Screen Shot 2022-11-10 at 1 44 46 PM" src="https://user-images.githubusercontent.com/54870020/201212248-38d656d9-5938-4a35-ab20-7178ca2146fe.png">

**Comment by dyf** [comment]
stack trace is probably good enough
