### ISSUE TITLE
Incorporate protocol_id into procedures model

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#188]
# User story
As a user, I want the protocol ids incorporated into the procedures models, so I can have proper metadata.

# Acceptance criteria
- [x] Given a user requests procedures information for a mouse, then it will be returned with the proper protocol_id if it is found.

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined
- [x] 2. Team understands acceptance criteria
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria
- [x] 4. Acceptance criteria is verifiable / testable
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
Moving this to blocked because we want to[ upgrade data-schema](https://github.com/AllenNeuralDynamics/aind-metadata-mapper/issues/37) before doing this. Reason we want to upgrade is due to this fix
