### ISSUE TITLE
Extract TARS identifiers from LabTracks RO injections and join with TARS metadata

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#193]
# User story
As a user, I want Labtracks procedures to include injection materials information. 

# Acceptance criteria
- [x] Given field in LAS tracking injection, map to injection procedure. 
- [ ] Given some field in LAS tracking injection materials, query tars.
- [ ] Given tars response, integrate viral material object back into procedure model. 

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
will need to parse out prep lot number from the comment

**Comment by jtyoung84** [comment]
Can you post some examples in Teams?

**Comment by mekhlakapoor** [comment]
Blocked because we need this info to be stored in a more reliable field in LAS

**Comment by mekhlakapoor** [comment]
LAS is going to add fields to the request form in sharepoint instead of Labtracks. Once they do, we'll need to add an endpoint to pull from the sharepoint

**Comment by mekhlakapoor** [comment]
Blocked: Need to add access to NSP sharepoint to our credentials or create new sharepoint credentials
