### ISSUE TITLE
Don't use model_construct

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#211]
# User story
As a developer, I want the pydantic models to validate correctly without recursion issues. Fix any model creations to not use model_construct

# Acceptance criteria
- [ ] Given procedures mappings, create models without model_construct

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
Check whether we can create invalid models with other method without it throwing validation errors at the time of creation

**Comment by jtyoung84** [comment]
Closing this for now as it will be sorted out in the V2 refactor.
