### ISSUE TITLE
Mice that were purchased need their source to reflect that

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-service#214]
**Is your feature request related to a problem? Please describe.**
Mice that were purchased lack breeding information in LabTracks. But if their source is given as AI, then the validator requires breeding information. The source should be where they were purchased from, which should be in LabTracks. (I expect it will always be JAX, but we should check)

**Describe the solution you'd like**
if a mouse do not have a breeding group, find the source of the mouse in LabTracks and ingest that information 

**Describe alternatives you've considered**

**Additional context**

**Comment by saskiad** [comment]
These are usually mice with 'wt/wt' genotypes

**Comment by dyf** [comment]
closing, dupe
