### ISSUE TITLE
Need to dynamically pull version number from pydantic models in unit tests

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#22]
**Describe the bug**
A unit test is failing because the pydantic model in aind_data_schema had a version bump.

**To Reproduce**
1. Run the unit tests.
2. An error occurs in the response handler
3. See error
```
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Subject
schema_version
  unexpected value; permitted: '0.2.1' (type=value_error.const; given=0.2.0; permitted=['0.2.1'])
```

**Expected behavior**
The unit tests should be passing.

**Additional context**
Maybe failing every time a dependent schema gets updated in `aind-data-schema` is the correct behavior?

**Comment by dyf** [comment]
We could pin the version of the `aind-data-schema` repo so that the service output only changes when we ask it to.

But, I wonder if this tests that enforce the shape of the output should rather be in `aind-data-schema`.

**Comment by jtyoung84** [comment]
There are two strategies we can take. 1) Pin the version `aind-data-schema` in the projects that import it and then update the version manually. 2) Pull in the latest version each time `aind-metadata-service` is getting deployed, allow the unit tests to fail, and then update `aind-metadata-service` to incorporate the changes in `aind-data-schema` before merging to main. I'm leaning towards the second strategy, but I can think about the pros and cons of each.

**Comment by jtyoung84** [comment]
This behavior is expected for now.
