### ISSUE TITLE
Upgrade pydantic version

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#221]
# User story
As a developer, I want to use the latest version of pydantic (2.7.0) because it has lots of useful features.

# Acceptance criteria
- [ ] Given pydantic 2.7, make any model and unit test updates as necessary

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by helen-m-lin** [comment]
Might be closed by another ticket.

**Comment by jtyoung84** [comment]
Already completed
