### ISSUE TITLE
Pull IP injections from LAS

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-service#236]
Need to get IP (Intraperitoneal) Injections injgested from LAS database. This is a subject procedure, already modeled in the schema.

**Comment by saskiad** [comment]
an example mouse is 737561

**Comment by saskiad** [comment]
no. It's a different thing. If there isn't already a ticket for that we can make one for that.

**Comment by mekhlakapoor** [comment]
> an example mouse is 737561


This subject id doesn't have an IP injection being tracked in the LAS sharepoint (I found that it has an RO injection though). Here's some example subject ids with IP injections: 744782, 744783, 745253, 745254
