### ISSUE TITLE
Query and Map 2023 sharepoint database for procedures

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#24]
NSB is rolling out a new database starting in January 2023.  

https://alleninstitute.sharepoint.com/BrainScience/IVS/Neurosurgery-Behavior/Lists/SWR%202023Present/New%20Request.aspx

We need to look for Procedure metadata there.  It has a different set of columns, so we will need to build a new mapping table.  Also, there will potentially be data for the same mouse in both the new and old database, so we will need to look in both places.

**Acceptance Criteria**

- [x] All Procedure metadata is still access through the same endpoint as before (no new endpoints)
- [x] Build a new mapping table against the 2023 database (skeleton mapping of basics)
- [x] For a single query, look for information in both databases and combine them into a single result
- [x] Return a schema-compliant Procedures JSON

**Comment by jtyoung84** [comment]
The `get_procedure_info` method in the SharePoint client will need to be independent of the Version (currently it's passed in as an arg). The `get_procedure_info` should take in a subject_id and loop through all the Versioned Lists for info to compile into a single Procedures model. The `default` in the Version enum should also be deleted.

**Comment by mekhlakapoor** [comment]
refactor into 2 classes (ResponseHandler2019, ResponseHandler2023)
