### ISSUE TITLE
procedures/713310 returns an internal server error

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#243]
**Describe the bug**
http://aind-metadata-service/procedures/713310 returns an internal server error

**To Reproduce**
1. Go to http://aind-metadata-service/procedures/713310
2. See error

**Expected behavior**
Data should be returned

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mekhlakapoor** [comment]
Pulling this into this sprint because I accidentally found this bug at the same time and resolved it in this PR #244

**Comment by mekhlakapoor** [comment]
This bug was fixed by #244
