### ISSUE TITLE
mouse 707254 has no surgical procedures

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#252]
There no procedures returned here:

http://aind-metadata-service/procedures/707254

But Kenta reports that there are procedures in NSB Sharepoint.

**Comment by mekhlakapoor** [comment]
Closing this issue. The reason 707254 is not finding any entries is because there is no request form in NSB with that as the labtracks id (it's in a comment right now). Kenta is creating a new request with all the info
