### ISSUE TITLE
Error fetching viral materials for 3 mice

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#260]
The second viral injection in both of these is not pulling virus information from TARS correctly. I see corresponding records in TARS, so not sure where the problem is coming from.  
 
http://aind-metadata-service/procedures/726441
http://aind-metadata-service/procedures/726649
http://aind-metadata-service/procedures/713862

**Comment by mekhlakapoor** [comment]
strip leading/trailing whitespaces, and special characters (ex: /t)
