### ISSUE TITLE
Map 2019 sharepoint database for procedures

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#27]
# User story
As a user, I want to map the 2019 sharepoint database, so I can have a more complete Procedures model instance.

# Acceptance criteria
- [ ] Access the 2019 DB through API
- [ ] Map all known fields for BrainInjection (iacuc_protocol, animal_weight, injection_duration, recovery_time, workstation_id, injection_type, injection_hemisphere, injection_coordinate_ml, injection_coordinate_ap, injection_coordinate_depth, injection_angle)
- [ ] map known fields for BrainInjection type Iontophoresis (injection_current, alternating_current)
- [ ]  map known fields for BrainInjection type Nanoject (injection_volume)
- [ ] map 2nd inj fields if it exists
- [ ] map known fields for Headplant/craniotomy
- [ ] map known fields for FiberImplant
- [ ] The SharePoint Client should have a mapping, as complete as possible, of the 2019 SharePoint DB into a Procedures model.
- [ ] Handle validation errors

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
broken down into #44 #45 #46 #47 #48
