### ISSUE TITLE
LAS procedures have a ghost procedure

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-service#270]
**Describe the bug**

**To Reproduce**
1. Go to metadata service
2. Enter 747335 into the subject id field for Procedure
3. Hit Search

It returns this:
{
  "describedBy": "https://raw.githubusercontent.com/AllenNeuralDynamics/aind-data-schema/main/src/aind_data_schema/core/procedures.py",
  "schema_version": "1.0.0",
  "subject_id": "747335",
  "subject_procedures": [
    {
      "procedure_type": "Surgery",
      "start_date": "2024-09-27",
      "experimenter_full_name": "30251",
      "iacuc_protocol": "2109",
      "animal_weight_prior": null,
      "animal_weight_post": null,
      "weight_unit": "gram",
      "anaesthesia": null,
      "workstation_id": null,
      "procedures": [
        {
          "procedure_type": "Perfusion",
          "output_specimen_ids": [
            "747335"
          ],
          "protocol_id": "dx.doi.org/10.17504/protocols.io.8epv51bejl1b/v6"
        }
      ],
      "notes": null
    },
    {
      "procedure_type": "Surgery",
      "start_date": "2024-09-27",
      "experimenter_full_name": "LAS-5018",
      "iacuc_protocol": "2109",
      "animal_weight_prior": null,
      "animal_weight_post": null,
      "weight_unit": "gram",
      "anaesthesia": null,
      "workstation_id": null,
      "procedures": [],
      "notes": null
    }
  ],
  "specimen_procedures": [],
  "notes": null
}

The second surgery here has not procedure information. it's on the same day as the perfusion, and has a LAS experimenter name. I don't think this is a real procedure and we should fix this.

Another example is 743916

**Comment by mekhlakapoor** [comment]
Closing out this issue as it's already been resolved in a duplicate ticket.
