### ISSUE TITLE
Ingest FiberProbe for fiber implant procedures

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-service#279]
- [ ] Minimum need a name for the probe. Auto generate these based on A/P coordinates. Eg. "Fiber 0", "Fiber 1" from A to P (If NSB adds a name field to the request form, use this, if not use A/P order)
- [x] NSB appears to have a "Standard" probe option. This must have values for the FiberProbe fields. Let's map these into the FiberProbe
- [x] Find our from NSB if there are other probe options and if so what their values are.

**Comment by dyf** [comment]
![image](https://github.com/user-attachments/assets/bd22cc81-98fa-4936-aa8b-332c7a2e8b21)

**Comment by mekhlakapoor** [comment]
Each burr hole (1-6) has 3 fields related to fiber probes: Fiber Type, Fiber Implant Length, and Fiber Implant D/V in addition to the regular burr hold fields (ML, AP, and 3 D/V fields). Right now the options for Fiber Type are Standard and Custom. There is no input field for the necessary data for Custom.

**Comment by mekhlakapoor** [comment]
These are the specs for the Standard implant type: 

Black ceramic ferrule for increased efficiency
and reduced autofluorescence.
1.25 mm ferrule diameter
200 um fiber core diameter. 
NA= 0.39

Custom specs are stored in comments?

**Comment by saskiad** [comment]
Double check the NA. I think Kenta said 0.37. (But I do trust Ali a bit more)

Custom specs coming in the comments is fine - what I gleaned from the email chain was that so far the custom fibers have differed in length but not the other specs, so what I worry about is how to know which specs to alter and which to keep standard.
