### ISSUE TITLE
Create custom status codes for responses

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#32]
# User story
As a user, I want to know which kind of response I get, so I can handle it appropriately.

# Acceptance criteria
- [ ] Come up with status codes for different types of responses.
- [ ] Document it thoroughly so users can quickly find the response types.
- [ ] Update the response module with the new status codes.

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined
- [x] 2. Team understands acceptance criteria
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria
- [x] 4. Acceptance criteria is verifiable / testable
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
A few are response we need to consider:

- Connecting to the backend error (aind-metadata-service tried to connect to labtracks/sharepoint but couldn't). Status Code: ???
- Backend server error (aind-metadata-service connected to the backend successfully, but something else went haywire). Status Code: ???
- Invalid data (aind-metadata-service retrieved some data, tried to validate using pydantic, but it didn't pass the validation check). Status Code: ???
- Multiple items found (aind-metadata-service queried the backend expecting one item returned, but multiple items were returned). Status Code: ???
- Valid Data (aind-metadata-service successfully retrieved valid data without any problems whatsoever). Status Code: 200

**Comment by mekhlakapoor** [comment]
update readme file to explain status codes
enum in response handler for status code
418
