### ISSUE TITLE
Add better way to get background strain

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-service#39]
# User story
As a user, I want a reliable way to retrieve the background strain given a subject id.

# Acceptance criteria
- [ ] Spend a day going through LabTracks to try to find background strain somewhere in LabTracks.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
Currently, we're pulling it from the maternal group name field, but this info is probably contained somewhere in a Labtrack's table.

It's possible this is not being tracked consistently.  Look at a several mice from different dates to be sure.  If there is no consistent place, we will work with Labtracks to figure this out.

**Comment by dyf** [comment]
This is an LAS issue, closing for now.
