### ISSUE TITLE
Map Missing Fields (not tracked in SWR)

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#84]
# User story
As a user, I want mapping to be as complete as possible. Try to figure out how to map these fields that are not tracked in SWR (can we assume some, fill in the gaps)

# Acceptance criteria
- [ ] Map Craniotomy coordinates and hemisphere for 2023 endpoint
- [ ] Map missing fields in 2019 endpoint for ophys probe (manufacturer, core_diameter, numerical_aperature, ferrule_material)
- [ ] Map duration for hp_anaesthesia
- [ ] map missing fields in 2019 endpoint for craniotomy (implant_part_number, protective_material) 

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*
- craniotomy coords can be inferred by type? provide protocol instead of coords
- ophys probe fields can also be inferred based on when NSB took over fibers

**Comment by saskiad** [comment]
craniotomy coordinates might not be realistic. I think we will need to rely on protocols having a diagram of the position/shape of the craniotomy for this - and metadata includes the protocol doi.

**Comment by dyf** [comment]
this has evolved, let's open new issues as needed
