### ISSUE TITLE
Map craniotomy size from craniotomy type instead of implant id/coverslip type

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-service#94]
The current mapping of craniotomy_size is incorrectly parsing the hyphen in implant id/coverslip type (ex in TS-4) as a negative value (ex: -4.0). This can be easily avoided by mapping craniotomy_size from SWR's craniotomy_type. 
 
```
craniotomy_size = parse_str_into_float(
    list_item.get_property(list_fields.CRANIOTOMY_TYPE.value)
)

```

**Comment by jtyoung84** [comment]
Might be resolved already...

**Comment by jtyoung84** [comment]
Closed by https://github.com/AllenNeuralDynamics/aind-metadata-service/pull/97
