### ISSUE TITLE
get non-surgical procedures performed by LAS into procedures

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-service#95]
These include retro-orbital injections, perfusion, tamoxifen dosing, post-surgical monitoring (?) 

Need to find the right contact in LAS about how these requests are stored.

**Comment by mekhlakapoor** [comment]
start with retro-orbital injections and perfusion. See if you can find ICV and ICM injections. Play around with SQL queries to find procedures in labtracks
